# Generated by Django 4.2.2 on 2023-07-03 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('english', 'English'), ('german', 'German')], default='german')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='word_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Word lists',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('list_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='words', to='deutsch.listcategory')),
                ('word_list', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='words', to='deutsch.wordlist')),
            ],
        ),
        migrations.AddField(
            model_name='listcategory',
            name='word_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='deutsch.wordlist'),
        ),
    ]
