# Generated by Django 4.2.2 on 2023-07-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deutsch', '0002_word_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listcategory',
            options={'ordering': ['order'], 'verbose_name_plural': 'List categories'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['word'], 'verbose_name_plural': 'Words'},
        ),
        migrations.AddField(
            model_name='word',
            name='translated_word',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
