# Generated by Django 4.2.2 on 2023-07-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deutsch', '0005_alter_word_list_category_alter_word_word_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='translated_word',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
