# Generated by Django 4.2.2 on 2023-07-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deutsch', '0006_alter_word_translated_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], default='de'),
        ),
    ]
